spring.application.name=concert-book

spring.datasource.url=jdbc:postgresql://localhost:5432/concert_book
spring.datasource.username=concert
spring.datasource.password=concert

spring.jpa.open-in-view=false